name: Auto Remove Labels

on:
  pull_request:
    types: [closed]

jobs:
  remove-labels:
    runs-on: ubuntu-latest

    steps:
    - name: Simple Issue Labeler
      uses: dangzo/labeler@1.0.2
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
        remove-labels: "need-review, Status:-in-progress, Status:-Needs-rebase, Status:-Need-help, Status:-Blocked"
        ignore-if-assigned: false


