name: Auto Remove Labels

on:
  pull_request:
    types: [closed]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Simple Issue Labeler
      uses: andymckay/labeler@1.0.2
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
        remove-labels: "Need review, Status: in progress, Status: Needs rebase, Status: Need help, Status: Blocked"
        ignore-if-assigned: false


